# Generated by Django 3.2.6 on 2021-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_opt', models.CharField(max_length=100)),
                ('size_opt', models.CharField(max_length=10)),
                ('item_code', models.CharField(max_length=100)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin_val', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_date', models.DateTimeField()),
            ],
        ),
    ]
