# Generated by Django 3.2.6 on 2021-08-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='bbb_stock',
        ),
    ]
